### ISSUE TITLE
Package incompatible with Laravel Sanctum

### ISSUE THREAD

**Issue by EriBloo** [bkremenovic/eloquent-tokens#1]
Hi.
This package has major drawback as it cannot be used on the same model that uses Laravel Sanctum\` `HasApiTokens`. Both your package and Sanctum have a method named `createToken`.

Do you think you can rename this method?

Greetings!

**Comment by bkremenovic** [comment]
Hi,
Thank you for bringing this up! You're correct that there is a naming conflict between the `createToken` method in this package and Laravel Sanctum's `HasApiTokens`. However, you can resolve this issue without requiring any immediate changes to the package by using PHP's `insteadof` keyword to specify which method to use.

Here’s an example of how you can handle this:
```
use HasEloquentTokens {
    HasEloquentTokens::createToken insteadof HasApiTokens;
}
```

This approach ensures that the `createToken` method from the `HasEloquentTokens` trait is used while still allowing you to take advantage of functionality from both traits. If you still need Sanctum's `createToken` method in some cases, you can **alias** it like this:
```
use HasApiTokens {
    HasApiTokens::createToken as sanctumCreateToken;
}
```

This way, both methods are accessible under different names, allowing you to use them side by side.

I understand that this can be a bit inconvenient, and I will consider renaming the method in a future release to avoid such conflicts. Thank you for bringing this to my attention!

Let me know if you need any further assistance. Thanks!

**Comment by EriBloo** [comment]
Thanks for a fast response. This is indeed approach I've taken. Only change I did was ~~renaming~~ aliasing your method. Are the any internal uses of this method inside your package that ~~rename~~ alias would break?

**Comment by bkremenovic** [comment]
Thanks for your update! Just to make sure we're on the same page, could you elaborate a bit on how you renamed the method? Specifically:

- Did you rename the method in the HasEloquentTokens trait directly?
- Or did you override it in your model and adjust references accordingly?

If it's the first case, renaming the method in the trait itself would technically work, but it’s not ideal (and it's an anti-pattern) since future updates to the package could overwrite your changes. If it's the second case, overriding the method in your model and referencing it as needed would be a safer long-term approach.

Let me know what approach you took, and I’ll confirm if there are any potential issues.

**Comment by EriBloo** [comment]
Sorry for the confusion. I **aliased** your method ;)

**Comment by bkremenovic** [comment]
You can safely proceed with the method aliasing approach, and everything should work as expected.
